/* 
RETORNA AS 10 OPERADORAS QUE MAIS TIVERAM DESPESAS COM 
"EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" NO ULTIMO TRIMESTRE
*/
SELECT dc_reg_ans AS OPERADORA, sum(dc_vl_saldo_final) AS TOTAL_DESPESAS FROM dem_contabeis dc 
WHERE dc_vl_saldo_final < 0 AND 
dc_descricao = "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" AND
dc_data > NOW() - INTERVAL 3 MONTH
GROUP BY dc_reg_ans
ORDER BY SUM(dc_vl_saldo_final) LIMIT 10;

/* 
RETORNA AS 10 OPERADORAS QUE MAIS TIVERAM DESPESAS COM 
"EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" NO ULTIMO ANO
*/
SELECT dc_reg_ans AS OPERADORA, sum(dc_vl_saldo_final) AS TOTAL_DESPESAS FROM dem_contabeis dc 
WHERE dc_vl_saldo_final < 0 AND 
dc_descricao LIKE "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" AND
dc_data > NOW() - INTERVAL 1 YEAR
GROUP BY dc_reg_ans
ORDER BY SUM(dc_vl_saldo_final) LIMIT 10;